services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
  nats:
    image: nats:2.7.2
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: [ "-js" ]
  registry:
    image: registry:2
    ports:
      - "5000:5000"